POST http://localhost:5000/user/register
Content-Type: application/json

{
  "username": "user",
  "email": "user@mail.com",
  "password": "!Password123"
}

###

POST http://localhost:5000/user/login
Content-Type: application/json

{
  "username": "user",
  "password": "!Password123"
}

###

GET http://localhost:5000/user/get-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZGM0ZWI2OWJiOWYyMDQxM2U1ZGUxMSIsImlhdCI6MTY1OTQ4NDgwOSwiZXhwIjoxNjU5NTA2NDA5fQ._sMRhKGg6r49sIN_dba9QpgwIP0KD8W0DopdZDJmLgM

###

POST http://localhost:5000/user/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDQ0MTZlZWE0NmM5OGY0MTUyOGQ1NiIsImlhdCI6MTY1ODI1MDA3OCwiZXhwIjoxNjU4MjcxNjc4fQ.KD3YQrgxEQfkLRNBdCA5oAV3yhCakg9LC2P936pj-UU

{
  "username": "user",
  "email": "user@mail.com"
}

###

POST http://localhost:5000/user/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDQ0MTZlZWE0NmM5OGY0MTUyOGQ1NiIsImlhdCI6MTY1ODI1MDA3OCwiZXhwIjoxNjU4MjcxNjc4fQ.KD3YQrgxEQfkLRNBdCA5oAV3yhCakg9LC2P936pj-UU

{
  "prevPassword": "password",
  "password": "!Password123"
}

###

DELETE http://localhost:5000/user/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDZlOTUyNjEwNDY2YTBlYTc0NGM1OCIsImlhdCI6MTY1ODI1MTYwNCwiZXhwIjoxNjU4MjczMjA0fQ.nkHd-YtiNH0q4Ewjckxk5grECX7FyBZ4ahLykMj9JEk

{
  "password": "!Password123"
}